### ISSUE TITLE
"$nick: ping?" doesn't trigger the script

### ISSUE THREAD

**Issue by djmitche** [floatingatoll/irssi-pingpong#9]
Allowing die-hard contentless-pingers to get away scot free :(

**Comment by floatingatoll** [comment]
Pull request declined, since /ping/ and /pingx?/ are both capable of matching 'pingx' (replace x with \?, same thing).

The issue is with `ping[\s\!\@\#\$\%\^\&\*\~0-9]*$`, which needs a question mark in the character class.

**Comment by djmitche** [comment]
fixed?
